### ISSUE TITLE
`sunraster.io` import error

### ISSUE THREAD

**Issue by wtbarnes** [glue-viz/glue-solar#35]
In the IRIS loader, there are numerous calls to `sunraster.io` which appears to no longer exist. This causes the plugin to fail to load when starting up glue.

I'm not sure where the equivalent IRIS loader functionality now lives. Perhaps in one of the IRIS-specific Python packages? https://gitlab.com/LMSAL_HUB/iris_hub

**Comment by nabobalis** [comment]
This has been fixed in main.
